### ISSUE TITLE
ed25519 addresses: remove amino, use SHA256[:20]

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-crypto#103]
This causes pain in https://github.com/tendermint/go-crypto/issues/77 and is included in https://github.com/tendermint/tendermint/issues/1568

Let's make the PubKeyEd25519.Address() return the first 20 bytes of the hash of the raw 32-byte pubkey, no amino required

See new `tmhash` for the hash function: https://github.com/tendermint/tmlibs/pull/210

**Comment by liamsi** [comment]
resolved via #112
