### ISSUE TITLE
Improve Ledger error handling, change PrivKey API

### ISSUE THREAD

**Issue by cwgoes** [tendermint/go-crypto#114]
At the moment, most of the `PrivKey` methods (`Sign`, `PubKey`) don't have a way to return errors, so we must panic if we can't query the Ledger. This will also be a problem with future HW wallets or any other kind of asynchronous signatures.

Changing these interfaces might be annoying downstream though.

**Comment by cwgoes** [comment]
Implemented in https://github.com/tendermint/go-crypto/pull/117.

**Comment by liamsi** [comment]
resolved in #117
added the changes we discussed a separate issue #129
