### ISSUE TITLE
Seed phrase has same last word  when create a new key

### ISSUE THREAD

**Issue by chengwenxi** [tendermint/go-crypto#116]
When I create a new key, it will return seed phrase with the same last word every time.
This should be caused by keybase.go#50,

`typ := cryptoAlgoToByte(algo)`
`secret = append([]byte{typ}, secret...)`

secret[0] is invariable, when BytesToWords, because of secret.length = 21 and words.length = 2048(2^11),  the last word index = f(secret.bits[21 * 8-11 * 15]) = f(secret.bits[3]) = f(secret[0].bits[0,2]),is also invariable.

`typ := cryptoAlgoToByte(algo)`
`secret = append(secret, []byte{typ}...)`
will avoid it.

**Comment by liamsi** [comment]
Thanks a lot for raising this issue! We are currently refactoring the code you mentioned and the key-type won’t be encoded in like above anymore. Also, we will only support Secp256k1 keys initially. This makes the whole key-type obsolete.

Related issues/discussions: https://github.com/tendermint/go-crypto/pull/85#discussion_r191945815 and https://github.com/tendermint/go-crypto/issues/89#issuecomment-392864261

**Comment by chengwenxi** [comment]
Yes, it's important to be compatible with cosmos fundraiser keys.

**Comment by liamsi** [comment]
This should be obsolete now!
