### ISSUE TITLE
HD Cleanup

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-crypto#12]
– Returns the secret twice: https://github.com/tendermint/go-crypto/blob/master/hd/address.go#L86

**Comment by odeke-em** [comment]
@ebuchman could you please elaborate for me what the problem is in the code snippet you point to?
<img width="1175" alt="screen shot 2017-07-26 at 9 06 28 pm" src="https://user-images.githubusercontent.com/4898263/28652662-56f4fc7a-7246-11e7-8782-a97b6f368a7e.png">

**Comment by ebuchman** [comment]
fixed here: https://github.com/tendermint/go-crypto/pull/59
