### ISSUE TITLE
Improve error message for the word codec?

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/go-crypto#124]
Would it be possible to improve the error message [here](https://github.com/tendermint/go-crypto/blob/develop/keys/words/wordcodec.go#L163) in the word codec? I haven't looked at the relevant part of the code to debug what the possible types of errors there are though, but the current error message isn't helpful for debugging what a user did wrong. (Though the cause of the error might be unclear)

For context, I was running:
```
$ democli keys add test --recover
Enter a passphrase for your key:
Repeat the passphrase:
Enter your recovery seed phrase:
apple banana cat dog
ERROR: Invalid data, could not have been generated by this codec
```

**Comment by liamsi** [comment]
Thanks dev! This code will be deleted in https://github.com/tendermint/go-crypto/pull/118
We will use a 3rd party library (https://github.com/bartekn/go-bip39) it would just return "Invalid mnemonic" I think. But we can change that (or add further hints what is wrong).
In your case ("apple banana cat dog"), we could show: mnemonic should be 12 (fundraiser) or 24 (fresh keys) words. I'll add some nicer error messages in #118

**Comment by ValarDragon** [comment]
Thanks Ismail! Sounds great

**Comment by ValarDragon** [comment]
Closing this issue, since it was handled with the key package update.
