### ISSUE TITLE
Proposal: minor API simplifications

### ISSUE THREAD

**Issue by liamsi** [tendermint/go-crypto#129]
- remove error from privKey.PublicKey(), if one already has the priv. key in hand the pub-key should be derivable from that without erroring: resolved via #131 
- remove the `Get*` in front of the `Info` interface methods: "it's neither idiomatic nor necessary to put Get into the getter's name." https://golang.org/doc/effective_go.html?#Getters

**Comment by cwgoes** [comment]
Agreed on both counts. Need to make sure we store and cache the public key when creating a remote private key (e.g. on the Ledger device) to fulfill this API.

**Comment by liamsi** [comment]
- error has been removed in #131 
- discussion regarding the getters should happen in cosmos-sdk

**Comment by cwgoes** [comment]
Moved to https://github.com/cosmos/cosmos-sdk/issues/1518.
