### ISSUE TITLE
Ed25519: Switch implementation to a C based implementation

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/go-crypto#140]
Our Ed25519 implementation benchmarks verification speed using a 11byte message. On my system, (2.8GHz, Intel i7 Kaby Lake, no other programs running), this took `193758` nanoseconds. 
Converting into verifications per second, this is `5161` verifications per second. (Note this could have been subject to external interference, since this is a Ubuntu install which likely had background programs running)

DJB's reference implementation (mentioned [here](https://ed25519.cr.yp.to/)): reports "273364 cycles to verify a <single> signature on Intel's widely deployed Nehalem/Westmere lines of CPUs".  At my laptops 2.8GHz rate, that translates to `10242` single verifications per second. These were benchmarked against 59 byte messages. (Length of messages matters, due to hashing involved)

This site https://bench.cr.yp.to/results-sign.html provides benchmarking across many different cpus. For the kaby lake cpu's, it reports `160085` cycles per verification, which is `17490` verifications per second at 2.8GHz. (Again on 59 byte messages)

It may be worth considering switching to using a C version in the future, and linking via Cgo. This could potentially yield a factor of 3 increase in efficiency. Bernstein's implementation also has the batch verification implemented, which could yield another factor of 2 efficiency increase. (This batch method can be implemented in go also, just hasn't been done yet). We could also modify the source, to include the method we've been discussing for caching the uncompression of the public key, to further increase verification speed. This would make sense to do if signature verification ever became a bottle neck.

**Comment by liamsi** [comment]
Cool. I'm in favour of a solid rust implementation and then compare that against an existing C version.
