### ISSUE TITLE
Move keybase to cosmos 

### ISSUE THREAD

**Issue by liamsi** [tendermint/go-crypto#141]
As discussed with @xla and @cwgoes:

- [x] delete keybase / ledger code from go-crypto (#142)
- [x] move keys/ledger-code to cosmos (make sure it is not used anywhere else first), ideally preserving the directory's git history
~~depends on #118~~ (merged)

Rationale: 
- get rid of the cgo dep. 
- move code to where it is used (cosmos-sdk/client/lcd)
- also, go-crypto & tendermint will get merged soon and we don't want the ledger/dependency live there
- moving the code over to cosmos-sdk will happen in https://github.com/cosmos/cosmos-sdk/pull/931 (by @cwgoes )

**Comment by cwgoes** [comment]
Merged, see https://github.com/tendermint/go-crypto/issues/143 for repo consolidation.
