### ISSUE TITLE
Repo consolidation

### ISSUE THREAD

**Issue by cwgoes** [tendermint/go-crypto#143]
In order:
1. Move remaining `go-crypto` functionality into Tendermint via PR to Tendermint (@Liamsi)
2. Make PR on SDK to import from Tendermint instead of from `go-crypto` and to include keybase / Ledger (@cwgoes)
3. Merge PRs
4. Profit!

**Comment by ValarDragon** [comment]
Do issues need to be recreated by hand by the respective issue creators?

**Comment by cwgoes** [comment]
> Do issues need to be recreated by hand by the respective issue creators?

Ideally we could port them automatically, perhaps with something like [this](https://github.com/google/github-issue-mover).

**Comment by liamsi** [comment]
resolved via 
https://github.com/cosmos/cosmos-sdk/pull/1386
https://github.com/cosmos/cosmos-sdk/pull/931
https://github.com/tendermint/tendermint/pull/1782
