### ISSUE TITLE
HD address scheme vs. Pubkey address scheme

### ISSUE THREAD

**Issue by mappum** [tendermint/go-crypto#21]
The current address scheme for the `PubKey` type is this: `ripemd160(pubKeyTypeByte + pubKeyBytes)`
(`+` is concatenation).

The scheme used in the Cosmos Fundraiser and in `go-crypto/hd` is this: `ripemd160(sha256(pubKeyBytes))` (and the keys use the secp256k1 curve).

Now we are getting to a point where we will need to use the Fundraiser addresses (the latter scheme) in Basecoin, which only uses the former. How do we plan on making this switch? Will we change `PubKey.Address()` to use the second scheme, breaking backwards compatibility for any basecoin apps? Or at genesis move coins from accounts based on the second scheme to accounts based on the first (possibly using the same key)?

**Comment by ebuchman** [comment]
We already support the proper scheme: https://github.com/tendermint/go-crypto/blob/master/pub_key.go#L125

**Comment by mappum** [comment]
Oh perfect, nevermind then. I had only been using ed25519 keys up until now, didn't realize the address function was different for different curves.
