### ISSUE TITLE
README: use godoc reference instead of hardcoded index/table-of-contents

### ISSUE THREAD

**Issue by odeke-em** [tendermint/go-crypto#24]
Currently the README consists of a hardcoded index, listing every exposed function's signature and containing a hardcoded link to the definition
<img width="1067" alt="screen shot 2017-07-26 at 3 56 10 pm" src="https://user-images.githubusercontent.com/4898263/28645519-0e650796-721b-11e7-8800-39124f60d2a1.png">

There are some problems with this:
1) The function definitions are hardcoded by line number ie
a) Click on https://github.com/tendermint/go-crypto#CRandBytes
<img width="739" alt="screen shot 2017-07-26 at 4 00 23 pm" src="https://user-images.githubusercontent.com/4898263/28645623-8e2a7fe2-721b-11e7-9e91-f03b8731563d.png">
b) Now click on the link to try to visit the function definition which is hardcoded to https://github.com/tendermint/go-crypto/blob/master/src/target/random.go?s=698:734#L28. That gives a 404
<img width="1097" alt="screen shot 2017-07-26 at 4 01 21 pm" src="https://user-images.githubusercontent.com/4898263/28645675-b1ecb3be-721b-11e7-9ce4-fc7a3267bf30.png">
2) A mere line change(addition or subtraction) disrupts the definitions
3) It is tedious to try to keep in sync with those definitions as exhibited in point 1) in which the file random.go no longer exists, but the new definition hasn't been changed in the README.

I propose we just switch to using godoc.org https://godoc.org/github.com/tendermint/go-crypto which is built exactly for this purpose so that we can easily navigate through Go source code with ease, they handle all the indexing for us and we don't have to worry at all about moving and keeping definitions in sync.

**Comment by zramsay** [comment]
closed in #25, #28

**Comment by odeke-em** [comment]
Thank you @zramsay for the reminder and close!
