### ISSUE TITLE
helpers: provide helpers to generate keys

### ISSUE THREAD

**Issue by odeke-em** [tendermint/go-crypto#31]
Am currently writing code to test out the bug fix for https://github.com/tendermint/tendermint/issues/514 in which we have a dishonest peer requesting a non-existent block height from a reactor and that requires a whole lot of setup.

I currently see that we have helpers for PrivKeyEd25519
https://github.com/tendermint/go-crypto/blob/1bc8de4caa844f8b64c120e65b047898f22b7f3e/priv_key.go#L99-L114

However, trying to generate the public key using our package is quite a bit of work, IMHO we should make it simple to generate a public Ed25519 key that conforms to our package and not just to the Go crypto library. I suspect some other developers might need this in the future.

**Comment by ethanfrey** [comment]
What about `GenPrivKeyEd25519().PubKey()`?

That's what I do, and your logic would do under the hood.  Not too much work, no?

**Comment by odeke-em** [comment]
Thanks @ethanfrey, and my apologies for the late reply, I was off from here since the weekend, but am back.

As per your recommendation and exhibit above, I've opened #35 in which we can provide a high level view of docs for go-crypto to easily transfer such knowledge to other developers and provide some more documentation. I'll close this issue in favor of the mentioned one.
