### ISSUE TITLE
Merge mintkey in

### ISSUE THREAD

**Issue by jaekwon** [tendermint/go-crypto#36]
We need to use bcrypt for cryptostore.
Lets merge in https://github.com/tendermint/mintkey/blob/master/cmd/mintkey/common.go

**Comment by ethanfrey** [comment]
This is noted in a comment.  I wasn't sure how to set up bcrypt securely, so I left it as a TODO until someone did it wrtie. (Better missing than buggy).  Could you make a PR to show me how?

The code to modify is here:
https://github.com/tendermint/go-crypto/blob/master/keys/cryptostore/encoder.go#L23-L26

I guess it should do something like:
https://github.com/tendermint/mintkey/blob/master/cmd/mintkey/common.go#L68-L77

But not sure how to deal with salts and headers. Also, we need to clean up the local file format as per #13 so maybe we should do that to add support for salts.

I don't know the proper design here.  Very happy to have someone with more experience in cryptography work on this.

**Comment by ethanfrey** [comment]
Is bcrypt even the right choice?

Scrypt seems much better against GPU cracking, and is in the go/x/crypto libs:
https://godoc.org/golang.org/x/crypto/scrypt

Or even other algorithms like argon2, the winner of the password hashing competition:
https://news.ycombinator.com/item?id=10863131

Notes on go implementations, which seem not really production-ready:
https://github.com/magical/argon2
https://github.com/golang/go/issues/19896

**Comment by adrianbrink** [comment]
This is implemented in #38

**Comment by adrianbrink** [comment]
I think we should stick with the proven crypto, which in this case is bcrypt. It has aged nicely for 14 years without any theoretical vulnerabilities. Scrypt with 3-4 is much less proven. It is more memory heavy and hence better against FPGA cracking. 

Some sources:
https://security.stackexchange.com/questions/26245/is-bcrypt-better-than-scrypt#26253

**Comment by ethanfrey** [comment]
It would be great to make this configurable somehow. At least bcrypt and scrypt. But I think that is related to #13

**Comment by adrianbrink** [comment]
I'll look into that once I have some time

**Comment by zramsay** [comment]
#38

**Comment by ebuchman** [comment]
configurable kdf is done in https://github.com/tendermint/go-crypto/pull/58 via the armor headers. we can add support for scrypt if we like down the road.
