### ISSUE TITLE
`MixEntropy` will reuse keys when called multiple times with the same source

### ISSUE THREAD

**Issue by mveytsman** [tendermint/go-crypto#39]
I'm a bit worried about how the random number generator implemented below works:

https://github.com/tendermint/go-crypto/blob/9016390a6e4d957b909650dbfa63b81510c3a68d/random.go#L59-L93

The PRNG uses a AES in CTR mode with a key derived from some other entropy source to encrypt the system random stream, producing a "mixed" random stream.

`MixEntropy` takes some bytes from the user, hashes them, and XORs the result with the key it keeps internally to create the new key. The initial key and every iv is generated from system random. 

This isn't fundamentally broken --- AES CTR from a good entropy source will be a good entropy source even if the key & iv are known, but it is overly complicated and I'm not sure if it adds anything.

But what happens if we call `MixEntropy` with the same input twice? i.e. 

https://github.com/tendermint/mintkey/blob/d057369af6fb9091bc240488a58d7ffdf35883d1/cmd/mintkey/gen.go#L36-L39 

asks us to "smash the keyboard" which can generate the same string when done repeatedly if you do what I like to call "naive keyboard bashing."

The key ends up being `initialKey ^ SHA256(NAIVEGARBAGE) ^ SHA256(NAIVEGARBAGE) = initialKey`. Repeating keys doesn't completely kill us here because we still use a system random IV for each iteration, and we're encrypting the system random stream, so we're only using the system entropy pool but we make things much more complicated.

One other thing to note is that if we're looking for keyboard bashing as a source of entropy, it's already factored into /dev/urandom on linux (I'm still researching if this is true on OSX but I believe it is). So we can actually have the keygen UI ask the user to bash the keyboard and wait a bit and then just pull from `crypto/rand` :)

The only reason I can see for using something other /dev/urandom is if you have a separate hardware rng you need to enable, but in this case you should wrap that in a Reader and just xor the output of your other Reader and `crypto/rand` together.

## Summary

1) While the scheme here isn't not obviously predictable it's non-standard and has some odd behaviour. I strongly recommend that we drop it in favour of using Go's crypto RNG.
2) If the requirement is to support keyboard bashing as an entropy source in the key generator, we can just ask the user to do this and know that it will affect the entropy pool (TODO: confirm on MacOS)
3) If the requirement is to accept a separate hardware rng, we should accept a reader and XOR it bitwise with `crypto/rand`, drastically simplifying this code. 
4) I actually thing point 3 is also a bad idea because you can use something like [rng-tools](https://wiki.archlinux.org/index.php/Rng-tools) to feed the kernel entropy pool from your hardware rng. E.g see this [guide](http://fios.sector16.net/hardware-rng-on-raspberry-pi/) for enabling the TRNG on a Raspberry Pi and mixing it into /dev/urandom. (TODO: if this is the requirement, research if there's an MacOS equivalent)

**Comment by silasdavis** [comment]
I agree with all of your proposals here. This code has bothered me in the past.

**Comment by ebuchman** [comment]
Thanks for raising this and sorry it took so long to address.

We addressed it in https://github.com/tendermint/go-crypto/pull/97 by hashing the old and new seedBytes together before using it in the AES. 

The point of this function is to protect against the possibility that the OS rng (crypto/rand) has itself been compromised.

That said, we're currently not using it anywhere, and it's use will be optional.
