### ISSUE TITLE
Folder not exit when install Basecoin

### ISSUE THREAD

**Issue by Max-Pano** [tendermint/go-crypto#52]
Hi, all
when I installing the Basecoin followed by the instruction, there is a fail that certain package found with a name "tendermint/go-crypto/cmd", the log is down below. does there a history version that contain the /cmd folder,  or what's you advise to do to solve this? thanks! 

package github.com/tendermint/go-crypto/cmd: cannot find package "github.com/tendermint/go-crypto/cmd" in any of:
        /usr/local/go/src/github.com/tendermint/go-crypto/cmd (from $GOROOT)
        /root/workspace/src/github.com/tendermint/go-crypto/cmd (from $GOPATH)

**Comment by zramsay** [comment]
which instruction are you following? ensure you've run `make get_vendor_deps` then `make install`

**Comment by odeke-em** [comment]
Ping @Max-Pano, @zramsay left some questions.

**Comment by zramsay** [comment]
closing as stale. @Max-Pano please re-open if you encounter the issue again
