### ISSUE TITLE
keys: Recover from seed without persisting to disk

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-crypto#57]
We should be able to enter a seed and use a privkey without that privkey ever being saved to disk

**Comment by ebuchman** [comment]
Oh - maybe that's just using memDB!

**Comment by ebuchman** [comment]
The recover flow should enable us to specify an HD path as well. See https://github.com/tendermint/go-crypto/issues/90

**Comment by liamsi** [comment]
> We should be able to enter a seed and use a privkey without that privkey ever being saved to disk

#118 tackles this the following way: if given an empty password, the (private) key is not persisted.

> The recover flow should enable us to specify an HD path as well. See #90

possible in #118 (BIP 44 is fully supported by keybase API, arbitrary BIP 32 paths are also supported via the hd package, i.e. without the persistence support etc)

**Comment by liamsi** [comment]
Possible via not providing a password to encrypt on disk (code moved over to cosmos-sdk).
