### ISSUE TITLE
Fork/Repo/Dep Management

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-crypto#60]
We have a fork of agl/ed25519 in tendermint/ed25519 and a fork of golang/x/crypto/bcrypt in here.

Let's instead fork golang.org/x/crypto and keep any changes we need in there.

We generally only need changes to support controlling input randomness:

- ed25519: need to MakePublicKey from self-generated priv key
- bcrypt: need to pass custom generated salt

x/crypto doesn't seem to support ToCurve25519 methods, so we can use agl/ed25519/extra25519 for those.

**Comment by ebuchman** [comment]
Note agl/ed25519 has diverged somewhat from https://godoc.org/golang.org/x/crypto/ed25519 (https://github.com/tendermint/ed25519/issues/2)

**Comment by ValarDragon** [comment]
Closing in favor of the tendermint issue.
