### ISSUE TITLE
Integration with bech32cosmos

### ISSUE THREAD

**Issue by zmanian** [tendermint/go-crypto#65]
Feature:

Go-crypto should be integrated with [bech32cosmos](https://github.com/cosmos/bech32cosmos)

String representation of cryptographic objects that come from go-crypto or are deserialized by go-crypto should only be provided in bech32cosmos form.

I think this is the right way to approach https://github.com/cosmos/cosmos-sdk/issues/263 but looking for confirmation.

**Comment by jaekwon** [comment]
Too many things... lets keep the discussion on https://github.com/cosmos/cosmos-sdk/issues/263 ,
and there is a PR at https://github.com/tendermint/go-crypto/pull/66
