### ISSUE TITLE
Integrate ThresholdPubKeys

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/go-crypto#67]
We should just make one PubKey be a ThresholdPubKey, so you can use PubKeyEd25519 or ThresholdPubKey, which can hold a PubKeyEd25519.

ThresholdPubKey has 2 fields… a slice of `type ThresholdPubKeyItem struct { PubKey, Power int64 }` and a `Threshold int64` too. (edited)

**Comment by jaekwon** [comment]
Wanna implement it?

**Comment by sunnya97** [comment]
Types I showed Zaki a few days ago:

`type SigSet struct {
    SigList []Sig
    WeightNeeded uint
}

type Sig struct {
    SigBytes crypto.Signature
    SigScheme string
    Weight uint
}`

**Comment by ValarDragon** [comment]
I am working on an ADR for this, however my proposal looks significantly different from this. I will refrain from posting an explanation right now, as I expect to have a PR with the ADR today / tomorrow.
