### ISSUE TITLE
Don't Panic!

### ISSUE THREAD

**Issue by silasdavis** [tendermint/go-crypto#69]
Currently code panics on errors in signing and generating keys. Whilst these errors might be unlikely they are not impossible and its not nice behaviour to take down a key-signing daemon just because there is a temporary issue with the entropy source, for example. Let's just return errors and let callers panic if they want to.

Happy to make PR for this.

**Comment by odeke-em** [comment]
Yeah, I have the same convictions and not a fan of seeing panics all around, I too would prefer errors. Thank you @silasdavis!

**Comment by ebuchman** [comment]
Should we change the Sign method to `Sign(msg []byte) (Signature, error)` then ? 

For certain things, panic seems fine - like errors on marshalling stuff that should not error. 

And it looks like we've mostly removed other panics on generating or signing, except for one in Secp - but that will require changing the method signature

**Comment by ValarDragon** [comment]
I support returning an error. This is in line with the return type of golang's signer interface. (`https://github.com/golang/go/blob/master/src/crypto/crypto.go#L115`)

**Comment by liamsi** [comment]
there are a few places left were go-crypto code panics but signing is addressed and resolved by #117
