### ISSUE TITLE
keys/types.go#readInfo should check for empty bytes

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-crypto#72]
Using this in the cosmos-sdk CLI gives indecipherable error when there's a simple typo in the key name

```
cosmos-sdk$ basecli keys show mykeyl
ERROR: EOF reading prefix bytes.
```

https://github.com/tendermint/go-crypto/blob/develop/keys/types.go#L53 should return a better error if the bytes are empty.

**Comment by ValarDragon** [comment]
This has been fixed
```
$ gaiacli keys show nonExistantKey
ERROR: Key nonExistantKey not found
```
