### ISSUE TITLE
ERROR tendermint/go-wire/data

### ISSUE THREAD

**Issue by asuleymanov** [tendermint/go-crypto#75]
Help. An error occurs when using the library.
../github.com/tendermint/go-crypto/priv_key.go:10:2: cannot find package "github.com/tendermint/go-wire/data" in any of:
        /opt/go/src/github.com/tendermint/go-wire/data (from $GOROOT)
        /home/ubuntu/workspace/src/github.com/tendermint/go-wire/data (from $GOPATH)
How to fix it?

**Comment by adrianbrink** [comment]
Which version of the library are you using and with what other pieces of our ecosystem (tmlibs, tendermint, ...)?

If you have an overall go project could you post your `Gopkg.toml` or `glide.yaml` file.

**Comment by asuleymanov** [comment]
Thank you very much for the answer. But I solved this problem.
