### ISSUE TITLE
Seedphrase Recover Issue

### ISSUE THREAD

**Issue by kidinamoto01** [tendermint/go-crypto#82]
the secret structure change from
```
[secret] = [secret] + [type] 
```
to
```
[secret] = [type] + [secret] 
```

which leads to key recover failure.

**Comment by ebuchman** [comment]
The address changed as well. 

Is it valuable to be able to recover old seeds even if it will lead to a different address ? 

See https://github.com/tendermint/go-crypto/issues/77 for ref
