### ISSUE TITLE
v0.6.x can't be used with Cosmos

### ISSUE THREAD

**Issue by schuyler** [tendermint/go-crypto#83]
Attempting to add it to a `Gopkg.toml` yields unresolvable constraints when running `dep ensure`.

cc @zmanian

**Comment by zmanian** [comment]
Try adding it using `[override]` directive rather than `[constrain]` directive

**Comment by ebuchman** [comment]
I believe this is fixed. Please re-open / new issue if I'm mistaken. Thanks!
