### ISSUE TITLE
keys: Expose HD tooling

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-crypto#90]
We need to be able to recover private keys from the words written down in the fundraiser, which used HD (bip32). We already have the HD code under `keys/hd` but we don't expose it in any tooling. 

We should have some way to specify an HD path when generating a secp256k1 key (note this only works for secp for now, not ed25519). 

This is specifically to facilitate offline transactions, eg https://github.com/cosmos/cosmos-sdk/issues/966

**Comment by liamsi** [comment]
possible via #118 (now living in cosmos-sdk).
