### ISSUE TITLE
Package _nano is never build, never used, and doesn't compile

### ISSUE THREAD

**Issue by liamsi** [tendermint/go-crypto#99]
copied over from https://github.com/tendermint/go-crypto/pull/96/files/ecc7cdfdf62350991fbfc092f2e51e4b1ee68091?utf8=%E2%9C%93&diff=unified#r188092482

the package _nano starts with an underscore. `go build` (and with it `go test`) completely ignores this package ...  (see https://golang.org/pkg/go/build/#Context.Import)

The package doesn't build (remove the underscore to reproduce). This is most probably due to: 
https://github.com/golang/go/issues/23672
and a dependency: 
```
go build github.com/ethanfrey/hid: invalid flag in #cgo LDFLAGS: -fconstant-cfstrings
FAIL    github.com/tendermint/go-crypto/nano [build failed]
```
related: https://github.com/ethanfrey/ledger/issues/1#issuecomment-368486919

**Comment by cwgoes** [comment]
Superseded by https://github.com/tendermint/go-crypto/pull/85 I think.

**Comment by liamsi** [comment]
Thanks! #85 would also resolve #93 and make #96 obsolete then /cc @jessysaurusrex @ebuchman

**Comment by cwgoes** [comment]
Yes, all the low-level Ledger communication code now lives in https://github.com/zondax/ledger-goclient.

**Comment by liamsi** [comment]
Makes much more sense to me, too.

**Comment by ebuchman** [comment]
Thanks guys
